# makefile for Boxcom's chassis



#------------------------- Done with configuration ---------------------

help:
	@echo "Makefile for Boxcom's chassis                             "
	@echo '                                                          '
	@echo 'Usage:                                                    '
	@echo '   make sticker              Make backside sticker        '
	@echo '                                                          '



